<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"> 
    <!-- <xacro:include filename="$(find ros2_livox_simulation)/urdf/mid360.xacro"/> 

    <xacro:mid360 name="livox" parent="base_link" topic="mid360">
        <origin xyz="${(base_length + length) / 2.0} 0 ${base_height / 2.0}"  rpy="0 0 0"/>
    </xacro:mid360> -->

    <xacro:include filename="sensors/livox.xacro"/>
    <xacro:sensor_livox name="livox_frame" parent="base_link" min_angle="-2.35619" max_angle="2.35619" samples="720">
      <origin xyz="0.0 0.0 0.0" rpy="${pi} 0.0 0.0"/>
    </xacro:sensor_livox>
    
</robot>